/* Template: Pricing Tier Table. Copy this file, edit it, add a script tag in index.html. */
Engine.templates.add('pricing-table', {
  "projectName": "Pricing Tier Table",
  "purpose": "A three-tier pricing comparison table.",
  "components": {
    "index.html": [
      "<!DOCTYPE html>",
      "<html lang='en'>",
      "<head><script src='https://cdn.tailwindcss.com'><\/script><\/head>",
      "<body class='bg-white py-20 px-4'>",
      "    <div class='max-w-6xl mx-auto text-center mb-12'>",
      "        <h2 class='text-4xl font-extrabold text-gray-900'>Simple, transparent pricing<\/h2>",
      "    <\/div>",
      "    <div class='max-w-5xl mx-auto grid md:grid-cols-3 gap-8'>",
      "        <div class='border border-gray-200 rounded-2xl p-8 flex flex-col'>",
      "            <h3 class='text-xl font-semibold mb-2'>Starter<\/h3>",
      "            <p class='text-4xl font-bold mb-6'>$0<span class='text-lg text-gray-500 font-normal'>/mo<\/span><\/p>",
      "            <ul class='space-y-3 mb-8 flex-1 text-gray-600'>",
      "                <li>✓ 1 User<\/li>",
      "                <li>✓ 5 Projects<\/li>",
      "                <li>✓ Basic Support<\/li>",
      "            <\/ul>",
      "            <button class='w-full py-2 bg-gray-100 text-gray-800 font-medium rounded-lg hover:bg-gray-200'>Get Started<\/button>",
      "        <\/div>",
      "        <div class='border-2 border-indigo-600 rounded-2xl p-8 flex flex-col relative transform md:-translate-y-4 shadow-xl'>",
      "            <div class='absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-indigo-600 text-white px-3 py-1 rounded-full text-xs font-bold uppercase'>Most Popular<\/div>",
      "            <h3 class='text-xl font-semibold mb-2'>Pro<\/h3>",
      "            <p class='text-4xl font-bold mb-6'>$29<span class='text-lg text-gray-500 font-normal'>/mo<\/span><\/p>",
      "            <ul class='space-y-3 mb-8 flex-1 text-gray-600'>",
      "                <li>✓ 5 Users<\/li>",
      "                <li>✓ Unlimited Projects<\/li>",
      "                <li>✓ Priority Support<\/li>",
      "                <li>✓ Advanced Analytics<\/li>",
      "            <\/ul>",
      "            <button class='w-full py-2 bg-indigo-600 text-white font-medium rounded-lg hover:bg-indigo-700'>Start Free Trial<\/button>",
      "        <\/div>",
      "        <div class='border border-gray-200 rounded-2xl p-8 flex flex-col'>",
      "            <h3 class='text-xl font-semibold mb-2'>Enterprise<\/h3>",
      "            <p class='text-4xl font-bold mb-6'>$99<span class='text-lg text-gray-500 font-normal'>/mo<\/span><\/p>",
      "            <ul class='space-y-3 mb-8 flex-1 text-gray-600'>",
      "                <li>✓ Unlimited Users<\/li>",
      "                <li>✓ Custom Integrations<\/li>",
      "                <li>✓ 24/7 Phone Support<\/li>",
      "            <\/ul>",
      "            <button class='w-full py-2 bg-gray-100 text-gray-800 font-medium rounded-lg hover:bg-gray-200'>Contact Sales<\/button>",
      "        <\/div>",
      "    <\/div>",
      "<\/body>",
      "<\/html>"
    ]
  }
});
